"""One-command setup: fetch a model, obtain whisper-server, write a config.

Targets the per-user data dir so it works whether SamWhispers was installed
from source or via pip/pipx. On Windows it downloads a prebuilt whisper.cpp
release (no Visual Studio needed); on Linux/macOS it builds from source (needs
git + cmake + a C++ compiler).
"""

from __future__ import annotations

import argparse
import io
import shutil
import subprocess
import sys
import zipfile
from pathlib import Path

import httpx

from samwhispers.history import resolve_data_dir
from samwhispers.models import WHISPER_CPP_MODELS, ModelDownloader
from samwhispers.webconfig import resolve_config_path

_WHISPER_REPO = "https://github.com/ggerganov/whisper.cpp.git"
# Stable "latest release" asset URL (no GitHub API / rate limit).
_WIN_PREBUILT_URL = (
    "https://github.com/ggerganov/whisper.cpp/releases/latest/download/whisper-bin-x64.zip"
)


def _paths() -> tuple[Path, Path, Path]:
    """(whisper_dir, models_dir, config_path)."""
    data = resolve_data_dir()
    return data / "whisper.cpp", data / "models", resolve_config_path()


def server_bin_path(whisper_dir: Path) -> Path:
    """Expected built binary path (``_resolve_server_bin`` finds the Windows variant)."""
    return whisper_dir / "build" / "bin" / "whisper-server"


def default_config_text(server_bin: Path, model_path: Path) -> str:
    return (
        "# Generated by `samwhispers-setup`. Edit freely, or use the web UI.\n"
        "[whisper]\n"
        "managed = true\n"
        'server_url = "http://localhost:8080"\n'
        f'server_bin = "{server_bin.as_posix()}"\n'
        f'model_path = "{model_path.as_posix()}"\n'
        'languages = ["auto"]\n'
    )


def write_config(
    config_path: Path, server_bin: Path, model_path: Path, force: bool = False
) -> bool:
    """Write a starter config. Returns True if written, False if left untouched."""
    if config_path.exists() and not force:
        return False
    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(default_config_text(server_bin, model_path), encoding="utf-8")
    return True


def ensure_model(model: str, models_dir: Path) -> Path:
    """Download ``ggml-<model>.bin`` into ``models_dir`` if missing."""
    dest = models_dir / f"ggml-{model}.bin"
    if dest.exists():
        return dest
    if model not in WHISPER_CPP_MODELS:
        raise SystemExit(f"Unknown model {model!r}; choose one of {WHISPER_CPP_MODELS}")
    print(f"Downloading model {model}...")
    downloader = ModelDownloader()
    downloader._state["downloading"] = True
    downloader._download(model, models_dir)
    status = downloader.status()
    if status["error"]:
        raise SystemExit(f"Model download failed: {status['error']}")
    return dest


def build_whisper_from_source(whisper_dir: Path) -> Path:
    """Clone (if needed) and build whisper.cpp; return the server binary path."""
    for tool in ("git", "cmake"):
        if shutil.which(tool) is None:
            raise SystemExit(
                f"'{tool}' is required to build whisper.cpp. Install it "
                "(e.g. `sudo apt install git cmake g++`) and re-run."
            )
    if not (whisper_dir / ".git").exists():
        print("Cloning whisper.cpp...")
        whisper_dir.parent.mkdir(parents=True, exist_ok=True)
        subprocess.run(
            ["git", "clone", "--depth", "1", _WHISPER_REPO, str(whisper_dir)], check=True
        )
    print("Building whisper.cpp (this can take a few minutes)...")
    subprocess.run(["cmake", "-B", "build"], cwd=whisper_dir, check=True)
    subprocess.run(
        ["cmake", "--build", "build", "--config", "Release", "-j"], cwd=whisper_dir, check=True
    )
    return server_bin_path(whisper_dir)


def download_whisper_prebuilt_windows(whisper_dir: Path) -> Path:
    """Download a prebuilt whisper.cpp release and return the server .exe path."""
    print("Downloading prebuilt whisper.cpp (Windows)...")
    dest = whisper_dir / "prebuilt"
    dest.mkdir(parents=True, exist_ok=True)
    with httpx.Client(follow_redirects=True, timeout=httpx.Timeout(30.0, read=300.0)) as client:
        resp = client.get(_WIN_PREBUILT_URL)
        resp.raise_for_status()
        zipfile.ZipFile(io.BytesIO(resp.content)).extractall(dest)
    matches = sorted(dest.rglob("*server*.exe"))
    if not matches:
        raise SystemExit(
            "Could not find whisper-server.exe in the prebuilt archive; "
            "build from source with --build instead."
        )
    return matches[0]


def ensure_whisper_server(whisper_dir: Path, build: bool) -> Path:
    """Locate or obtain the whisper-server binary."""
    existing = server_bin_path(whisper_dir)
    if existing.exists():
        return existing
    if sys.platform == "win32" and not build:
        return download_whisper_prebuilt_windows(whisper_dir)
    return build_whisper_from_source(whisper_dir)


def main() -> None:
    parser = argparse.ArgumentParser(
        prog="samwhispers-setup",
        description="Set up whisper-server, a model, and a starter config.",
    )
    parser.add_argument("--model", default="base.en", help="Model to download (default base.en)")
    parser.add_argument(
        "--build", action="store_true", help="Build whisper.cpp from source even on Windows"
    )
    parser.add_argument(
        "--force-config", action="store_true", help="Overwrite an existing config.toml"
    )
    args = parser.parse_args()

    whisper_dir, models_dir, config_path = _paths()
    server_bin = ensure_whisper_server(whisper_dir, build=args.build)
    model_path = ensure_model(args.model, models_dir)
    wrote = write_config(config_path, server_bin, model_path, force=args.force_config)

    print("\nSetup complete.")
    print(f"  whisper-server: {server_bin}")
    print(f"  model:          {model_path}")
    print(f"  config:         {config_path}" + ("" if wrote else " (kept existing)"))
    print("\nNext:")
    print("  samwhispers-supervisor       # run now (tray + web UI)")
    print("  samwhispers-autostart enable # start automatically at login")


if __name__ == "__main__":
    main()
